In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [4]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.39109355, -0.37945145, -0.09789154, -0.39371583,  0.49668083,
         0.18255416,  0.69561976,  0.06842838, -0.11772512,  0.10613167]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.2027225

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.2984 - accuracy: 0.9121
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1456 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1092 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 12s 7ms/step - loss: 0.0893 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0781 - accuracy: 0.9758


In [11]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0778 - accuracy: 0.9765


[0.07782428711652756, 0.9764999747276306]

In [12]:
probablity_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [14]:
probablity_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.6853356e-08, 6.2333831e-09, 2.4225715e-06, 1.7779339e-04,
        1.1755845e-09, 1.5762792e-07, 1.0419754e-12, 9.9981135e-01,
        1.2611136e-07, 8.0971158e-06],
       [1.8107142e-08, 2.7129106e-04, 9.9934810e-01, 3.5704215e-04,
        1.4623094e-14, 2.1466900e-05, 9.3904316e-07, 5.2730327e-11,
        1.1589577e-06, 1.7379280e-13],
       [3.4529214e-07, 9.9582088e-01, 4.4387919e-04, 2.7784959e-05,
        1.9291017e-04, 1.2017363e-05, 3.4044209e-05, 3.1207670e-03,
        3.4526398e-04, 2.0926984e-06],
       [9.9961072e-01, 5.3297509e-09, 3.9966108e-05, 1.0229199e-07,
        2.0849482e-07, 2.0463590e-06, 3.3683027e-04, 7.0446413e-06,
        2.3421281e-07, 2.9216928e-06],
       [3.9297217e-07, 1.0160506e-10, 8.8198725e-08, 5.2339582e-09,
        9.9897623e-01, 3.8401893e-08, 3.3300091e-06, 2.8686345e-05,
        5.8255338e-08, 9.9119113e-04]], dtype=float32)>